cvz/urls.py
from django.urls import path
from carecenter import views as user_views
from .views import (
    Appointment_Table_For_Receptionists_TodayArchiveView,
    Appointment_Table_For_carecenter_TodayArchiveView,
    TimeSlotCreateView,
    Booking_appointment_In_CareCenter_CreateView,

    EmployeeListView,
    EmployeeDetailView,
    EmployeeCreateView,
    EmployeeUpdateView,
    EmployeeDeleteView,

    CareCenter_Head_TodayArchiveView,
CareCenterSignUpView,
CareCenterCreateView,
Doctor_For_HeadDetailView,
Doctor_For_HeadUpdateView,
CareCenter_For_HeadUpdateView,
TimeSlotUpdateView,

)
from . import views
from users import views as user_views1
#from users.views import Table1ListView

urlpatterns = [
#Creating User Id  For CareCenter
    path('accounts/signup/reception/', user_views.CareCenterSignUpView.as_view(), name='reception_signup'),
#Creating Profile(detail) For CareCenter
    path('CareCenter_as_user_profile/', user_views.CareCenter_as_user_profile, name='CareCenter_as_user_profile'),


# CareCenter

    path('CareCenter/', Appointment_Table_For_Receptionists_TodayArchiveView.as_view(), name='CareCenter'),

    path('Appointment_Table_For_carecenter/<int:pk>/', Appointment_Table_For_carecenter_TodayArchiveView.as_view(),
         name='Appointment_Table_For_carecenter'),

    path('Appointment_Table_For_carecenter/<int:pk>/<int:str>/Booking_Appointment_form/', Booking_appointment_In_CareCenter_CreateView.as_view(),
         name='Booking_Appointment_form'),

# Creating User From Carecenter
    path('Appointment_Table_For_carecenter/<int:pk>/<int:str>/Booking_Appointment_form/user_register/', user_views.register_user, name='register'),



# Creating TimeSlots
    path('Appointment_Table_For_carecenter/<int:pk>/TimeSlotCreated_by_CareCenter/', TimeSlotCreateView.as_view(),
         name='timeslot_form'),

    path('TimeSlotUpdateView/<int:pk>/', TimeSlotUpdateView.as_view(),
         name='TimeSlot_update'),



# Center__Head   (This Links Are Shown or used only for Head

    path('CareCenter_Head/', CareCenter_Head_TodayArchiveView.as_view(),
         name='CareCenter_Head'),

    path('CareCenterCreateView_IN_HEAD/', CareCenterSignUpView.as_view(), name='CareCenterSignUp'),

    path('CareCenterCreateView_IN_HEAD/create', CareCenterCreateView.as_view(), name='CareCenterCreate'),

    path('DoctorDetail_For_HeadView/<int:pk>/', Doctor_For_HeadDetailView.as_view(),
         name='Doctor_For_HeadDetailView'),
    path('Doctor_For_HeadUpdateView/<int:pk>/', Doctor_For_HeadUpdateView.as_view(),
         name='Doctor_For_HeadUpdateView'),

    path('CareCenter_For_HeadUpdateView/<int:pk>/', CareCenter_For_HeadUpdateView.as_view(),
         name='CareCenter_For_HeadUpdateView'),

    path('create_Head/', user_views.Create, name='Create'),


#CareCenter_employee
    path('employee_list/', EmployeeListView.as_view(), name='Employee'),
    path('employee_detail/<int:pk>/', EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee/new/<int:pk>/', EmployeeCreateView.as_view(), name='employee_form'),
    path('employee/<int:pk>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', EmployeeDeleteView.as_view(), name='employee_delete'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

from users.views import (
    Table1DetailView,
    Table1CreateView,
    Table1UpdateView,
    Table1DeleteView,
    UserTable1ListView,

)

admin.site.site_header = "DRE Admin"
admin.site.site_title = "DRE Admin Panel"
admin.site.index_title = "Welcome to DRE Admin Panel"


#from django.conf.urls import  url



urlpatterns = [
    path('admin/', admin.site.urls),



    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', user_views.SignUpView.as_view(), name='signup'),





    path('register/', user_views.register, name='register'),


    path('search/', user_views.search, name='search'),

    path('shop/handlerequest/', user_views.handlerequest, name='handlerequest'),
    #
    #


#



    # For Create btn inside today page



    path('Table1/<int:pk>/', Table1DetailView.as_view(), name='Table1_detail'),









# For Users in doctors profile
    path('doctors_profile/<int:pk>/<int:str>/Table1_form/', Table1CreateView.as_view(), name='Appointment_Table_form'),

    path('Table1/<int:pk>/update/', Table1UpdateView.as_view(), name='Appointment_Table_update'),
    path('Table1/<int:pk>/delete/', Table1DeleteView.as_view(), name='Table1_confirm_delete'),
    path('user/<str:username>//', UserTable1ListView.as_view(), name='user_Table1s'),


    path('appointmentsearch/', user_views.appointmentsearch, name='appointmentsearch'),
    path('appointments/', user_views.appointments, name='appointments'),

    # Comment

    path('profile_update/', user_views.profile_update, name='profile_update'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='blog/home.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),


    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),


    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),


    path('', include('blog.urls')),
    path('', include('video_call_chats.urls')),
    path('', include('doctor.urls')),
    path('', include('carecenter.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from doctor.models import *

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone

from django.db import models
#class User(AbstractUser):
 #   is_profile = models.BooleanField(default=False)
  #  is_doctor = models.BooleanField(default=False)
   # is_CareCenter = models.BooleanField(default=False)


from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager


#This For All Type OF User's
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100)
    First_Name = models.CharField(max_length=128, blank=True)
    Last_Name = models.CharField(max_length=128, blank=True)
    phone_number = models.IntegerField( blank=True, null=True)
    email = models.CharField(_('email address'),max_length=128, unique=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    is_doctor = models.BooleanField(default=False)
    is_CareCenter = models.BooleanField(default=False)
    CareCenter_Head = models.BooleanField(default=False)


    Company_staff_1 = models.BooleanField(default=False)
    Company_staff_2 = models.BooleanField(default=False)
    Company_staff_3 = models.BooleanField(default=False)

#Attachement purpose
    is_doctor_a = models.CharField(max_length=128, blank=True, null=True)
    is_CareCenter_a = models.CharField(max_length=128, blank=True, null=True)
    CareCenter_Head_a = models.CharField(max_length=128, blank=True, null=True)


    Company_staff_1_a = models.CharField(max_length=128, blank=True, null=True)
    Company_staff_2_a = models.CharField(max_length=128, blank=True, null=True)
    Company_staff_3_a = models.CharField(max_length=128, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return str(self.email)
     # return self.id

#User's Profile
class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE )
    First_Name = models.CharField(max_length=128, blank=True)
    Last_Name = models.CharField(max_length=128, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', blank=True, null=True)
    birth_date = models.DateField( blank=True, null=True)
    phone_number = models.IntegerField(default='+91', blank=True)

    def __str__(self):
        return f'{self.user.email} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 100 or img.width > 50:
            output_size = (100, 50)
            img.thumbnail(output_size)
            img.save(self.image.path)




from carecenter.models import CareCenter

from doctor.models import doctor
#Appointment_Timeslots
class Timeslots(models.Model):
    title = models.CharField(default='Available',max_length=200)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    appointment_date = models.DateField(default=timezone.now)
    no = models.CharField(max_length=1000)
    available = models.BooleanField(default=True)
    doctors_profile = models.ForeignKey(doctor, on_delete=models.CASCADE)


    class Meta:
        ordering = ['start_time']

    def __str__(self):
        return '%s - %s' % (self.start_time.strftime("%I:%M %p"), self.end_time.strftime("%I:%M %p"))

class Appointment_Table(models.Model):
    patient_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='patient_name')
    doctors_profile = models.ForeignKey(doctor, on_delete=models.CASCADE)
    CareCenter = models.ForeignKey(CareCenter, on_delete=models.CASCADE)
    timeslots = models.OneToOneField(Timeslots, on_delete=models.CASCADE )
    First_Name = models.CharField(max_length=128)
    Last_Name = models.CharField(max_length=128)
    receipt = models.FileField(upload_to='prescription_receipts', null=True, blank=True)
    Writing_prescription = models.TextField(max_length=10000, null=True, blank=True)
    no = models.CharField(max_length=1000)
    mode = models.CharField(max_length=200, choices=(
          ('In Clinic', 'In Clinic'),('online(Video Calling)','online(Video Calling)'),) ,default='cash on center')
    Amount = models.CharField(max_length=100)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    appointment_date = models.DateField()

    def __str__(self):
        return self.id

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from .models import Profile, doctor, Appointment_Table
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import  User, doctor
from django.contrib.auth.forms import UserCreationForm
from .models import User, CustomUser
from django.contrib.auth import get_user_model

User = get_user_model()


from django.contrib.auth import login
from django.shortcuts import render,reverse, redirect, HttpResponse, get_object_or_404

class UserRegisterForm(UserCreationForm):
    First_Name = forms.CharField( label='First Name', widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    Last_Name = forms.CharField( label='Last Name', widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    phone_number = forms.IntegerField( widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))
    email = forms.CharField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email/Phone'}))
    class Meta:
        model = User
        fields = [ 'First_Name', 'Last_Name','phone_number', 'email', 'password1' ]

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_profile = True
        user.save()
        return user
    def form_valid(self, form):
        user = form.save()

        login(self.request, user)
        return redirect('/')




class UserUpdateForm(forms.ModelForm):
   # username = models.CharField(max_length='128')
    class Meta:
        model = User
        fields = [ 'phone_number', 'First_Name','Last_Name']



class ProfileUpdateForm(forms.ModelForm):


    birth_date = forms.DateField()

    class Meta:
        model = Profile
        fields = ['birth_date', 'image']










from django.forms import ModelForm, DateInput
from .models import Timeslots

users/templates/users/Table1_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block body %}


<!-- Header   Of Home page -->
<div class="Entire-Header">
  <!-- This is the Menu (Hamburger menu) which was showing on the top-->
    <nav role="navigation">
        <div class="logo" ><a href="{% url 'home' %}" style="color:black;">EVE</a></div>
 <!--  <button type="submit" class="sgnup">Sign Up</button>  -->
      <div id="menuToggle">
      <input type="checkbox" />
      <span></span>
      <span></span>
      <span></span>
      <ul id="menu">
       <div id="profile">
           <a  href="{% url 'profile' %}"><li>
             <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
             <p>Hello, {{ request.user.First_Name }}</p></li></a>
       </div>

           <a href="{% url 'home' %}"><li>Home</li></a><hr/>
           <a href="{% url 'post' %}" ><li>Health Blog</li></a></hr>
<hr/>       {% if user.is_authenticated %}

           <a href="{% url 'logout' %}"><li>Logout</li></a><hr/>
          {% else %}
           <a href="{% url 'login' %}"><li>Log In</li></a><hr/>
           <a href="{% url 'register' %}"><li>Sign Up</li></a><hr/>
          {% endif %}
      </ul>
     </div>
    </nav>
</div>

<style>
  /* Logo For Desktop */
  @media(min-width:450px) and (max-width:3000px){
  .Entire-Header{
    height:40px;
  }
  
  .logo{
    display:block;
    font-size:25px;
    font-weight:700;
    text-align: left;
    padding-left: 50px;
    padding-top:0px;
    }
  #menuToggle
  {
    display: fixed;
    position: relative;
    top: -8px;
    left: 10px;
    z-index: 1;
    color:rgb(240, 226, 226);
    -webkit-user-select: none;
    user-select: none;
  }
  
  }
/* For Mobile */
@media(max-width:450px){
.Entire-Header{
  height:40px;
}

.logo{
  display:block;
  font-size:1.8rem;
  font-weight:600;
  }
#menuToggle
{
  display: fixed;
  position: relative;
  top: -10px;
  left: 10px;
  z-index: 1;
  color:rgb(240, 226, 226);
  -webkit-user-select: none;
  user-select: none;
}

}
</style>
<!--End Of Header -->



<!-- Appointment Detail Start-->

<div class="detail-box">
         {% if object.doctors_profile.user == user %}
    <div class="detailtopcontainer">
        <div class="appdetail">
         <p class="patient-detail">User Name: {{ object.patient_name }}</p>
         <p class="patient-detail">Patient Name: {{ object.your_name }}</p>

          <p class="date-detail">{{ object.for_date|date:"F d, Y" }}</p>

          <p class="timing-detail">{{ object.timeslot }}</p>
          <p class="timing-detail">{{ object.timeslot.0 }}</p>

          <p class="no-detail" >No.-{{ object.no }}</p>
            <p class="no-detail" >Payment-{{ object.payment }}</p>

          <p class="doctor-detail">By  -Dr.{{ object.doctors_profile }}</p>

          <p class="doctor-detail">By  -Dr.{{ object.receipt }}<a  target="_blank"  href="/media/profile_pics/{{ object.receipt }}" >Download Receipt</a></p>

    </div>
    
    <div class="detailupdate">
 
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'Appointment_Table_update' object.id %}">Update</a>

  <!--    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'Table1_confirm_delete' object.id %}">Delete</a>
  -->
  </div>
     {% endif %}
  </div>


<!-- For PAtient -->
<div class="detail-box">
  {% if object.patient_name == user %}
<div class="detailtopcontainer">
 <div class="appdetail">
  <p class="patient-detail">User Name: {{ object.patient_name }}</p>
  <p class="patient-detail">Patient Name: {{ object.First_Name }} {{ object.Last_Name }}</p>

   <p class="date-detail">{{ object.appointment_date|date:"F d, Y" }}</p>
   <p class="no-detail" >No. {{ object.no }}</p>
   <p class="no-detail" >Timing:  {{ object.start_time|date:'H:i A' }}-{{ object.end_time|date:'H:i A' }}</p>
     <p class="no-detail" >Amount-{{ object.doctors_profile.fee }}</p>

   <p class="doctor-detail">By  -Dr.<a href="{% url 'doctors_profile_archive' object.doctors_profile.id %}">{{ object.doctors_profile.First_Name }} {{ object.doctors_profile.Last_Name }}</a></p>

   <p class="doctor-detail"> Prescription: <a href="/media/profile_pics/{{ object.receipt }}" target="_blank">Download Prescription</a></p>


<embed src="media/profile_pics/prescription_receipts/purchase_d1gmail.com.pdf" type="application/pdf" width="100%" height="100px" />
 </div>
</div>

{% endif %}
</div>






<style>

/* for desktop */
@media(min-width:450px) and (max-width:3000px){
.detail-box{
    display:block;
    background-color: rgb(243, 243, 243);
}

.detailtopcontainer{
    height: 470px;
    border-top: none;
  }
.appdetail{
    float:left;
    padding-left: 1rem;
    padding-top: 1rem;
  }
.patient-detail{
    font-size: 20px;
    font-weight: 600;
}
.patientname-detail{
    font-size: 20px;
    font-weight: 650;
    color: black;
}
.date-detail{
  font-size: 15px;
  color:rgb(121, 121, 121);
}
.no-detail{
  font-size: 15px;
  font-weight: 500;
  color:rgb(15, 15, 15);
}
.doctor-detail{
    font-size: 20px;
    font-weight: 600;
    color: black;
}

.timing-detail{
  font-size: 15px;
  color:rgb(121, 121, 121);
}


.detailupdate{
  padding-left: 5rem;
}
}


/* for mobile  */
@media(max-width:450px){
.detailtopcontainer{
    height: 500px;


  }
.detail-box{
    display:block;
    background-color: rgb(230, 230, 230);
}

.appdetail{

    float:left;
    padding-left: 3px;
    padding-top: 3px;
  }
.patient-detail{

    font-size: 20px;
    font-weight: 600;
}
.patientname-detail{
    margin-top:-10px;
    font-size: 25px;
    font-weight: 650;
    color: black;
}
.date-detail{
  margin-top:-10px;
  font-size: 20px;
  color:rgb(0, 0, 0);
  font-weight: 600;
}
.timing-detail{
  margin-top:-10px;
  font-size: 20px;
  color:rgb(0, 0, 0);
  font-weight: 600;
}

.no-detail{
  margin-top:-10px;
  font-size: 20px;
  font-weight: 600;
  color:rgb(15, 15, 15);
}
.doctor-detail{
  margin-top:-10px;
  font-size: 20px;
    font-weight: 800;
    color: black;
}


.imgdetail{
 width:66%;

  }
.imgdetail p{
    font-size:20px;
    font-weight: 600;
    font-family: Arial, Helvetica, sans-serif;
  }
.imgdetail img{
    height:500px;
    width:150%;
    justify-content: center;
  }

.detailupdate{
  font-size:25px;
  padding-left: 5rem;
}
}
</style>







<!-- Footer     --------->
<hr/>
<div class="footer-container-page">
    <section class="footer-page">
      <div class="footerlinks-page" >
         <a href="{% url 'about' %}"> About Us</a>
     </div>

     <div class="footerlinks-page">
        <a href="{% url 'contact' %}"> Contact </a>
     </div>

     <div class="footerlinks-page">
        <a href="{% url 'contact' %}">Add Your Clinic/Hospital</a>
     </div>

    </section>

    <div class="socialcontainer-page">
      <a href="#"><img class="socialmedia-page" src="{% static 'images/facebook.png' %}" /></a>
      <a href="#"><img class="socialmedia-page" src="{% static 'images/instagram.png' %}" /></a>
      <a href="#"><img class="socialmedia-page" src="{% static 'images/twitter.png' %}" /></a>
    </div>

    <main class="lastline-page">
     <span class="credit"> <a href="#">EVE </a>|</span>
       <img class="socialmedia" id="copyright" src="{% static 'images/copyright.png' %}" />
       2021 All rights reserved.
    </main>

</div>

<!--Css Of Footer-->
<style type="text/css">

  /* for desktop */
  @media(min-width:450px) and (max-width:3000px){
    .footer-container-page{
      display:block;
      text-align:center;
     }
    .footer-page{
      justify-content:center;
      display:flex;
    }
    .footerlinks-page{
      padding-left:40px;

    }
    .footerlinks-page a{
      color:rgb(153, 153, 153);
      font-size: xx-small;
    }
    .socialmedia-page{
      height:20px;
      width:50px;
      padding-left:30px;
    }
    .lastline-page a{
      font-size: 15px;
      color:#000000;
    }
    .lastline-page{
      font-size: xx-small;
      color:#929292;
    }
    #copyright{
      height:15px;
      width:15px;
    }
  }


    /*Footer-page for mobile  */

    @media(max-width:450px){
    .footer-container-page{
      display:block;
      text-align:center;
     }
    .footer-page{
      justify-content:center;
      display:flex;
    }
    .footerlinks-page{
      padding-left:10px;

    }
    .footerlinks-page a{
      color:rgb(153, 153, 153);
      font-size: xx-small;
    }
    .socialmedia-page{
      height:20px;
      width:50px;
      padding-left:30px;
    }
    .lastline-page a{
      font-size: 15px;
      font-weight: 700;
      color:#080808;
    }
    .lastline-page{
      font-size: xx-small;
      color:#929292;
    }
    #copyright{
      height:15px;
      width:15px;
    }
  }
  </style>
  <!--End Of Footer-for-page-->

{% endblock %}

users/templates/users/doctors_app_email.html
EVE Health Care Centers

Patient : {{ your_name|safe  }}

Wating No. : {{ no|safe  }}

schedule: {{ timing|safe|striptags }}

On Date: {{ for_date|safe  }}

Issues: {{ issue|safe  }}

Paid Amount: {{ payment|safe  }}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block body %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}

<style type="text/css">
#id_birth_date{
  height:30px;

}
#id_your_name{
  height:30px;

}
#id_username{
  height:30px;
}
#id_email{
  height:30px;
}
#id_password2{
  height:30px;

}
#id_password1{
  height:30px;

}
#hint_id_username{
    display:none;
}
#hint_id_password2{
    display:none;
}
body {
    background: #fafafa;
}
    
   
/* for desktop */
@media(min-width:450px) and (max-width:3000px){
.content-section{
        margin-top:-100px;
        text-align: center;
        color:rgb(0, 0, 0);
        margin-left:35%;
        height:500px;
        width:300px;
        border-style: solid;
        border-radius: 1px;
        border-width: 1px;
        border-color:rgb(211, 211, 211);
}
.asteriskField{
        display:none; 
}    
.login-header{
        color:rgb(0, 0, 0);
}
.login-header H2{
       font-size: 3rem;
       font-weight: 800;
       padding-left: 30px;
}    
.signup-field{
      margin-top: -20px;
}
.form-group{
        padding-left: 20px;
        padding-right: 20px;
        text-align: center;
        display:center;
        justify-content: center;    
}
}
    
/* for mobile  */
@media(max-width:450px){
.content-section{
        margin-top:-10px;
        text-align: center;
        color:rgb(0, 0, 0);
        margin-left:13%;
        height:500px;
        width:300px;
        border-style: solid;
        border-radius: 1px;
        border-width: 1px;
        border-color:rgb(211, 211, 211);
        background-color: rgb(247, 247, 247);
}
.asteriskField{
        display:none; 
}    
.login-header{
        color:rgb(0, 0, 0);
        text-align: center;
}
.login-header H2{
       font-size: 3rem;
       font-weight: 800;
}    
.login-header p{
        margin-top:-15px;
}
.signup-field{
    margin-top:-20px;      
}
.form-group{
        padding-left: 20px;
        padding-right: 20px;
        text-align: center;
        display:center;
        justify-content: center;
    
}
}
</style>
        
    
        <div class="login-header">
            <H2>EVE</H2>
            <p>Health Care Centers</p>
        </div>
    <div class="content-section">
           <form method="POST" >
                {% csrf_token %}
              <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                <div class="formfill">

                    <div class="signup-field">
                        {{ form.First_Name|as_crispy_field }}
                    </div>

                    <div class="signup-field">
                        {{ form.Last_Name|as_crispy_field }}
                    </div>
                    <div class="signup-field">
                        {{ form.phone_number|as_crispy_field }}
                    </div>
                    <div class="signup-field">
                        {{ form.email|as_crispy_field }}
                    </div>

                    <div class="signup-field">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="signup-field">
                        {{ form.password2|as_crispy_field }}
                    </div>
                    </div>
              </fieldset>
              <div class="form-group">
                <button style="height:30px;  width:150px; margin-top:-20px;" class="btn btn-primary"  type="submit">Sign In</button>
              </div>
            </form>


        <small class="text-muted1">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Log In</a>
            </small>
    </div>
    
    















    
    <!-- Footer     --------->
    <hr/>
    
        <main class="lastline-page">
         <span class="credit"> <a href="#">EVE </a>|</span>
           <img class="socialmedia" id="copyright" src="{% static 'images/copyright.png' %}" />
           2021 All rights reserved.
        </main>
    
    </div>
    <!--Css Of Footer-->
    <style type="text/css">
    
      /* for desktop */
      @media(min-width:450px) and (max-width:3000px){
        .lastline-page a{
          font-size: 15px;
          color:#000000;
        }
        .lastline-page{
          text-align:center;  
          font-size: xx-small;
          color:#929292;
        }
        #copyright{
          height:15px;
          width:15px;
        }
      }
    
    
        /*Footer-page for mobile  */
    
        @media(max-width:450px){
    
    
        .lastline-page{
      
          text-align:center;  
          font-size: xx-small;
          color:#929292;
        }
        .lastline-page a{
          font-size: 15px;
          color:#000000;
        }
        #copyright{
          height:15px;
          width:15px;
        }
      }
      </style>
{% endblock %}

users/templates/users/user_id_pass_in_email.html
EVE Health Care Centers

email : {{ email|safe  }}

password : {{ password|safe  }}